### ISSUE TITLE
Cannot find pug.png on Mint an NFT on Stellar side quest

### ISSUE THREAD

**Issue by aysenazemirhan** [altugbakan/stellar-quest-go#2]
![image](https://user-images.githubusercontent.com/113712189/199826381-99ab1111-0924-4830-991d-5a9b677843fa.png)

**Comment by altugbakan** [comment]
Hello,

It should work when you run the script from the main folder, i.e. `C:\Users\User\stellar-quest-go-main` using `go run ./side_quests/mint_an_nft_on_stellar` on your case.

I will try to come up with a solution for running the program in the folder soon.

<hr>

Merhaba,

Ana klasörden, yani sizin durumunuzda `C:\Users\User\stellar-quest-go-main` klasöründen `go run ./side_quests/mint_an_nft_on_stellar` ile çalıştırıldığında sorun çözülebilir.

Klasörde çalıştırıldığında da çalışmasını sağlayacak bir çözüm bulacağım.
