### ISSUE TITLE
Soroban Quests

### ISSUE THREAD

**Issue by aysenazemirhan** [altugbakan/stellar-quest-go#3]
yeni görevler içinde hazırlarmısınız https://github.com/tyvdh/soroban-quest--pioneer

**Comment by altugbakan** [comment]
I am not sure if I can support the next quest's solutions using Go. Please contact me on Discord (Sjox#0001) for personal questions.

<hr>

Yeni sorular için çözümleri Go ile sağlayabileceğimden emin değilim. Kişisel sorularınız için bana Discord (Sjox#0001) üzerinden ulaşabilirsiniz.
